### ISSUE TITLE
tmp folder location should not assume /tmp

### ISSUE THREAD

**Issue by durzo** [trampgeek/moodle-qtype_coderunner#101]
There are a couple of places in code calling tempnam() with /tmp as the path, this should be replaced with moodle's make_request_directory() which creates and returns a folder inside $CFG->localcachedir that is automatically removed once the php execution has finished.

Many Moodle Partners do not condone plugins writing to /tmp, and we specifically size our servers to have restricted /tmp with relatively small partition sizes compared to the configured $CFG->localcachedir path for moodle to use.

At the very least, you should use $CFG->tempdir if you feel make_request_directory() is not adequate.

**Comment by trampgeek** [comment]
Thanks for the heads-up. As it turns out, though, none of the uses of /tmp should be occurring in normal coderunner use. Most were in a piece of legacy code: an unused abstract class to support local sandboxes. I've deleted that file from the project. The only other instance was in a script used, AFAIK, only my myself, which supports ICPC-style programming contest questions. But I've updated that one anyway, along the lines you suggest. 

The changes will appear in the next version pushed to github and the plugins repository.
