### ISSUE TITLE
Problem upgrading from 3.7.5 to 3.7.9

### ISSUE THREAD

**Issue by mrcinv** [trampgeek/moodle-qtype_coderunner#103]
I can't upgrade coderuner from version 3.7.5(2020012500) to 3.7.9(2020080300) or any version higher for that matter. When I try to update the database, I get the following error:
```
Coding error detected, it must be fixed by a programmer: You can only set identifiers on initial definition creation. Define a new cache to set different identifiers.

More information about this error
Debug info:
Error code: codingerror
Stack trace:

    line 792 of /cache/classes/definition.php: coding_exception thrown
    line 255 of /cache/disabledlib.php: call to cache_definition->set_identifiers()
    line 182 of /cache/classes/loaders.php: call to cache_factory_disabled->create_cache_from_definition()
    line 461 of /question/engine/bank.php: call to cache::make()
    line 468 of /question/engine/bank.php: call to question_finder->get_data_cache()
    line 245 of /question/engine/bank.php: call to question_finder->uncache_question()
    line 651 of /question/type/coderunner/questiontype.php: call to question_bank::notify_question_edited()
    line 278 of /question/type/coderunner/questiontype.php: call to qtype_coderunner->notify_prototype_children_if_any()
    line 458 of /question/format.php: call to qtype_coderunner->save_question_options()
    line 195 of /question/type/coderunner/db/upgradelib.php: call to qformat_default->importprocess()
    line 158 of /question/type/coderunner/db/upgradelib.php: call to load_questions()
    line 50 of /question/type/coderunner/db/upgradelib.php: call to load_new_prototypes()
    line 342 of /question/type/coderunner/db/upgrade.php: call to update_question_types()
    line 692 of /lib/upgradelib.php: call to xmldb_qtype_coderunner_upgrade()
    line 1917 of /lib/upgradelib.php: call to upgrade_plugins()
    line 713 of /admin/index.php: call to upgrade_noncore()
```
Here is a screenshot:

![upgrading_database_after_coderunner_update](https://user-images.githubusercontent.com/5948013/94252112-c60e8500-ff23-11ea-84a0-8fe1f0adf195.png)

**Comment by trampgeek** [comment]
I'm hoping Tim Hunt can cast some light on this problem.

During a CodeRunner upgrade I delete all the existing question prototypes and re-import the latest versions. As each prototype is imported, all questions of that type are deleted from the cache (because the cached version contains information from the previous version of the prototype). On your system it appears the cache is disabled and in that case a call to the _uncache_question()_ method of the _question_finder_ class leads to the exception you're seeing.

It seems to me that the cache is probably not meant to be disabled at this stage in a question type upgrade and/or there is a bug in the handling of _uncache_question_ if the cache is disabled.

Can you think of any reason why your Moodle system might be disabling the cache when other systems do not?

**Comment by mrcinv** [comment]
Nothing in my configuration or filrsystem would suggest that the cache is disabled. I didn't change anything reguarding cache in moodle administration.

**Comment by trampgeek** [comment]
We could bypass the cache-invalidation during the upgrade but I'd like to understand what's happening here. No-one else has reported such problems.

A few questions, please.

1. What OS are you using?
1. What Moodle version are you running?
1. Is the server running OK in all other respects? In particular, can you edit questions (CodeRunner or otherwise)?
1. What procedure are you using to upgrade CodeRunner?

Also, if I'm to suggest actions you might take, I'd like to know where this is a critical production server or an experimental server.

**Comment by mrcinv** [comment]
Let me answer your questions:
1. linux debian 10
2. Moodle 3.9.2+ (Build: 20200918)
3. Coderunner is missing some prototype questions(python3, java_method, etc.) after reverting unsuccessfull update to previous version. I can edit other questions just fine. I can also edit coderunner questions if I select one of the remaining types (c_function, cpp_function, cpp_program, c_program, directed_graph). Server dosn't seem to have other problems.
4. I've used upgrade button in moodle (/admin/plugins.php?updatesonly=1&contribonly=0)
and also manualy extracting plugin files in  `/question/type/coderunner` and then updating database in moodle. Allways with the same result.

The server is to become critical production server on October the 1st.

**Comment by trampgeek** [comment]
Time is tight, then. We don't have time for much further exploration or attempts to replicate your problem. So ... how adventurous are you feeling? I'm 99% confident that the following procedure will get you up and running again but there's alway some level of uncertainty. **Proceed at your own risk**.

1. Backup your server.
1. Manually extract the plugin files as you did before but _before_ updating in Moodle comment out line 651 in <moodlehome>/question/type/coderunner/questiontype.php. It should be the line

    question_bank::notify_question_edited($child->questionid);

    **Do not proceed if it's anything else.**
1. Proceed with the Moodle database update.
1. Uncomment line 651 (i.e. restore it to its original state).
1. Use _Site Administration > Development > Purge all caches_ to clear the cache manually.

To explain: the line you're commenting out has the role of clearing from Moodle's cache any questions that depend on the prototypes being edited (or in this case reloaded from scratch). It's not a particularly critical line of code; it's relevant only when you edit prototypes. Purging all caches after the upgrade achieves the same effect. The line you're commenting out is the one triggering your exception, apparently because the cache is disabled during the update process. I still don't understand why this is happening to you, but we don't have time to explore further. Tim Hunt ... are you there? Do you have any thoughts on this?

**Comment by mrcinv** [comment]
Thank you very much for the workaround. It works now, there are 19 prototype questions and all seems to work now. 
Let me know If I could be of any further assistance.

**Comment by trampgeek** [comment]
Good to know that worked. I've now managed to replicate the problem by upgrading my development system from 3.9 to 3.9.2. It seems a change to the Moodle cache subsystem a couple of weeks ago causes the problem (around about Moodle version 3.9.1+). I've added a workaround to CodeRunner that prevents invalidating the cache entry for a question if the cache is disabled, e.g. during updates I've pushed that to github but will hold back a day or two before pushing a new version of coderunner to the plugins repository.

Thanks for reporting the problem.
