### ISSUE TITLE
resultcolumns_help example isn't accurate

### ISSUE THREAD

**Issue by lucaboesch** [trampgeek/moodle-qtype_coderunner#108]
In the resultcolumns_help text, the example given for the resultcolumns field, which according to the documentation must be a JSON-encoded list of column specifiers is told to be [["Test", "testcode"],​["Input", "stdin"], ["Expected",
"expected"], ["Got", "got"]].
Now, that isn't a JSON-encoded list. And it wouldn't work either.

It would be great if that flaw in documentation could be fixed.

Thanks in advance,
Luca

**Comment by trampgeek** [comment]
I don't really understand the problem here. The string

    [["Test", "testcode"], ["Input", "stdin"], ["Expected","expected"], ["Got", "got"]]

is valid JSON according to jsonlint.com. Is it the layout within the help system that's concerning you, or what?

Also, if I use exactly that string in the _Result columns_ field of the author editing form, it works fine for me, as do variants like 

    [["Test code", "testcode"], ["Standard Input", "stdin"], ["Wanted","expected"], ["Received", "got"]]

However, as noted in the in-line help, the Result column setting is ignored when using a combinator template grader, because the question author then defines the exact format of the result table in the template.

Could you clarify exactly what you'd like to see changed, please.
