### ISSUE TITLE
Getting NameError: name 'quiet' is not defined with Python3 when creating a new Python 3

### ISSUE THREAD

**Issue by kulttuuri** [trampgeek/moodle-qtype_coderunner#124]
Hi!

Great plugin! However, got an issue with the latest release 4.0.2. With 4.0.1 all worked well, but now after upgrading to release 4.0.2 I am getting this error when trying to create a new question with a type of Python3 and trying to run it. My question is only basic ``print("I love programming")``. Importing and running old questions still works.

This "quiet" related to some change made some commits back.. ?

```
Syntax Error(s)
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/py_compile.py", line 144, in compile
    code = loader.source_to_code(source_bytes, dfile or file,
  File "", line 846, in source_to_code
  File "", line 219, in _call_with_frames_removed
  File "__tester__.python3", line 7
    I love programming
      ^
SyntaxError: invalid syntax

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/py_compile.py", line 209, in main
    compile(filename, doraise=True)
  File "/usr/local/lib/python3.8/py_compile.py", line 150, in compile
    raise py_exc
__main__.PyCompileError:   File "__tester__.python3", line 7
    I love programming
      ^
SyntaxError: invalid syntax


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/local/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/usr/local/lib/python3.8/py_compile.py", line 218, in 
    sys.exit(main())
  File "/usr/local/lib/python3.8/py_compile.py", line 213, in main
    if quiet < 2:
NameError: name 'quiet' is not defined
```

**Comment by kulttuuri** [comment]
And FYI this is Python 3.8.5 I am running on the server. Locked the version to this so that none of my pip packages would break. Could probably be an old version or some pip package missing... ?

**Comment by trampgeek** [comment]
The NameError 'quiet' is not defined is a bug in the PyCompile module in older versions of Python. See here: https://bugs.python.org/issue38731 . I had a temporary work-around for this in the Jobe server v 1.6.4 but removed it again in Jobe version 1.6.6 as the bug is now fixed in the most recent Python.  By running Python 3.8.5 you've reactivated the bug.

However, that error message is just a side effect of the main bug, which is the Syntax Error at the top - you can ignore everything after about line 9 - the bit about name quiet being not defined is just noise.

The syntax error suggests that you're trying to run a Python programming that is simply

    I love programming

Can you send me an XML export of the question you're trying to run, please?

**Comment by kulttuuri** [comment]
Yeah – that was it! I was trying to fill the answer into the "Test Case" field instead of "Expected output" and was caught unguard with that error message. I will also update to a more recent Python version to prevent this error message from generating and giving headaches to other teachers around.

Thank you Richard for the fast and great response to this issue! 👍  :)
