### ISSUE TITLE
Problems connecting to Jobe Server if Coderunner version is higher than 3.7.9+

### ISSUE THREAD

**Issue by TomSemilia** [trampgeek/moodle-qtype_coderunner#135]
Hey!
I am running a dedicated jobe server on the newest version and I am not able to connect from moodle to it if my Coderunner version is higher than 3.7.9+.
Do you have any idea what is causing this and how to fix that?
Best regards,
Tommy

**Comment by trampgeek** [comment]
No, I don't know what the problem is. It seems a bit unlikely that it's a problem related to the version of CodeRunner; if the problem occurred after an upgrade to a more recent CodeRunner, I'd suspect that some other settings changed at the same time.

Please provide more info as follows:

 * What sequence of events (e.g. Moodle and/or CodeRunner version upgrades, Jobe server upgrades etc) led to the problem?
 * What exactly is the failure mode? Please provide a screen shot.
 * Does your Moodle work with the default Jobe server (jobe2.cosc.canterbury.ac.nz) at the University of Canterbury? You will also need to set the API key to the default (2AAA7A5415B4A9B394B54BF1D2E9D) to access this server.
 * Please copy the test file [testsubmit.py](https://github.com/trampgeek/jobe/blob/master/testsubmit.py) to your Moodle server, edit line 52 so that it references your Jobe server rather than localhost, and run it with the command

        python3 testsubmit.py

    What happens?

**Comment by trampgeek** [comment]
Closing as no response for 7 months.
