### ISSUE TITLE
Timeout when uploading support files when an HTTP proxy is used

### ISSUE THREAD

**Issue by matteodellamico** [trampgeek/moodle-qtype_coderunner#167]
Hi, and thanks a lot for this great project!

I'm trying to set up CodeRunner on a server that relies on an HTTP proxy for communication between Moodle and Jobe. There is an issue when we try to run questions that require support files, in particular Moodle timeouts and then gives an error. Questions without support files seem to run fine instead.

The Jobe server returns the following error:
```
Host: [redacted]
Accept-Encoding: deflate, gzip, br
Content-Type: application/json; charset=utf-8
Accept-Charset: utf-8
Accept: application/json
X-CodeRunner-Job-Id: 2fcb3380
User-Agent: MoodleBot/4.1 (+https://test.aulaweb.unige.it)
Content-Length: 441
Via: 1.1 vm-proxy:8080 (squid/2.7.STABLE7)
X-Forwarded-For: [redacted]
Cache-Control: max-age=259200
Connection: keep-alive

{"run_spec":{"language_id":"python3","sourcecode":"def sqr(x):\r\n return x*x\n\n__student_answer__ = \"\"\"def sqr(x):\r\n return x*x\"\"\"\n\nSEPARATOR = \"#<ab@17943918#@>#\"\n\nprint(sqr(3))\nprint(SEPARATOR)\nprint(sqr(-3))\nprint(SEPARATOR)\nprint(sqr(\"3\"))\nprint(SEPARATOR)\nprint(sqr(42))\n\n","sourcefilename":"__tester__.python3","input":"\n","file_list":[["7c2af6065e470dd253936c8d0dcb26cc","test1.py"]],"parameters":[]}}HTTP/1.0 404 Not Found

Date: Thu, 20 Apr 2023 12:27:34 GMT
Server: Apache/2.4.41 (Ubuntu)
Access-Control-Allow-Origin: *
Access-Control-Allow-Headers: X-API-KEY, Origin, X-Requested-With, Content-Type, Accept, Access-Control-Request-Method
Access-Control-Allow-Methods: GET, POST, OPTIONS, PUT, HEAD, DELETE
Content-Length: 60
Connection: close
Content-Type: application/json; charset=utf-8

"One or more of the specified files is missing\/unavailable"
```

I am not a PHP expert but I tried to track down this error, which I understand is returned on the Jobe side by `load_files` in `LanguageTask.php`, called by `files_put` in `Restapi.php`.

If I am not wrong, this is called on the Moodle side by `put_file` in `jobesandbox.php`, and the comments indeed mention that the plugin doesn't use the Moodle curl class but rather the raw PHP curl. Could it be possible that is the reason why the HTTP proxy is not used, and hence that the HTTP PUT is not seen by our Jobe server?

If this is the case and this is indeed a CodeRunner issue, of course it would be great to see it fixed, but we would like to deploy CodeRunner on our next academic year, and we'd be grateful even for a "quick and dirty" patch that could work for us. Thanks a lot!

**Comment by trampgeek** [comment]
Its hard to know exactly what the problem is here. 

The network traffic example you quote is apparently for the original POST request to Jobe and there's nothing wrong there - it should indeed return 404 if the requested file (test1.py with the id "7c2af6065e470dd253936c8d0dcb26cc", which is the md5 hash of the file contents) is not present in Jobe's file cache. The Jobe protocol then requires that the initiator (Moodle/CodeRunner in this case) follows with a PUT request containing the file itself. If that succeeds (as it should), the POST is repeated.

Presumably it's the PUT that is failing.

Can I just confirm exactly what is happening, please? 

1. From what you say, I assume you have a question with an author-supplied attached file.
2. If the question has a sample answer, "Validate on save" is checked, and the PUT is failing, you should just see _Failed to run tests_ in red, below the answer.
3. If you turn off validate on save, or delete the answer, you should then be able to save. But when you try running the question, you see _An unexpected error occurs. The sandbox may be down. Try again shortly._ after the answer and below, in the result table, _Jobe server request failed. One or more of the specified files is missing/unavailable_. 

Is that the situation?

If so, it's almost certainly the PUT that is failing but I doubt that's because it's using raw PHP curl - that usually gives fewer problems than the moodle Curl class, because the latter has a lot of extra security checks.

The simplest explanation would be that the proxy server is not configured to handle HTTP PUT requests, or perhaps just doesn't work correctly with them. Are you able to check that first? 

If that's not the problem then my next guess is that the firewall on the Moodle server itself is disallowing outgoing PUTs.

I'm not sure I can be much more help that that, sorry. No-one else is reporting this problem, so I think it's most likely a consequence of your particular network configuration rather than the coding of CodeRunner.

**Comment by Hyrla** [comment]
We had the same issue and didn't find a valid solution. We simply bypassed our proxy for CodeRunner/Jobe requests to make it work. I hope someone will find a better solution regarding this problem

**Comment by trampgeek** [comment]
There's a very similar issue just reported on the coderunner forum: https://coderunner.org.nz/mod/forum/discuss.php?d=632#p2603

The poster there solved the problem simply by changing the Jobe URL on Moodle from HTTP to HTTPS.
