### ISSUE TITLE
Problem on running ACE inline JS in the CodeRunner jobe server

### ISSUE THREAD

**Issue by feerposser** [trampgeek/moodle-qtype_coderunner#170]
Hey, every one!

My team is facing a weird problem on running JS using ACE inline filter. We can create questions using all available languages, but when we're using ACE inline filter we get the error message below just when running JS code:
![image](https://github.com/trampgeek/moodle-qtype_coderunner/assets/14969618/8ce674aa-361f-4f5f-a079-e11f10349da9)

Researching for this error, it look like [the problem is in the CodeRunner sandbox Jobe Server](https://coderunner.org.nz/mod/forum/discuss.php?d=67) and not in the ACE inline filter. But I really dont understand how this is happening because the JS code on CodeRunner questions are running normally.

Can someone help me to understand how solve this problem? 

Thanks (:

**Comment by trampgeek** [comment]
The problem here is that Jobe knows the language as "nodejs" rather than just "javascript". If you use _lang="nodejs"_ in your _pre_ element I think you'll find it works fine.

Sorry about the confusion. I've added the following sentence to the [demo page](https://coderunner.org.nz/mod/page/view.php?id=545&forceview=1) on coderunner.org.nz: 

    Available languages are those built into the Jobe server: python2, python3, c, cpp, java, nodejs (javascript), octave, pascal, php.

But we should also map the language names _js_ and _javascript_ to _nodejs_.

Thanks for reporting.
