### ISSUE TITLE
Code Runner on Moodle 

### ISSUE THREAD

**Issue by selarem** [trampgeek/moodle-qtype_coderunner#227]
Dear Support Team,

I am currently utilizing the Code Runner on Moodle for conducting Python programming exercises. These exercises involve writing codes for specified tasks. For instance, if an exercise requires writing four methods for a given class, I create test cases for each method.

However, I encounter an issue where if an error occurs in one test, the corresponding test case fails to execute or produces an unexpected result. Consequently, subsequent test cases are not evaluated. I have attempted to address this by selecting the "Hide the rest on failure" option, but the issue persists.

Thank you for your assistance.

Best regards,
sea

**Comment by trampgeek** [comment]
If a test gives a runtime error, further testing is aborted. This is by design to prevent, for example, repeatedly getting a compile error on each test. 

Usually, the error message issued to the student on the first failure is sufficient for them to correct their code and resubmit. You can adjust the penalty regime to give zero or minimal penalties for the first few submissions if you wish.

If you really wish to continue running tests after a runtime error, you should try to restructure your tests so that runtime errors (or output to the stderr stream which is taken as equivalent to a runtime error) is avoided. The strategy depends on the language and on the particular sort of exception you're prepared to tolerate. You might, for example, want to wrap your test in a try ... catch structure. 

FYI, the best place to ask questions of this sort is the question author's forum on coderunner.org.nz.
