### ISSUE TITLE
Supporting older data format of coderunner database

### ISSUE THREAD

**Issue by kcleung** [trampgeek/moodle-qtype_coderunner#38]
As you can see, Coderunner is a project with fast-evolving features and formats.  It is increasingly being used by many institutes, which often run long courses that can span for more than a year.  Also, I've talked to a lot of sysadmins, and they don't have the opportunity to update the servers (often once a year, or less), and their attitude tend to be "don't touch it unless you have to".  Therefore by the time they update the server, a lot of formats have already changed in coderunner, and things become broken.

Therefore in my opinion, we can't assume that course only have a short lifetime, and remove support of legacy formats at will during refactoring.  We need to at least be able to read the old data, with or without converting them to the new format.

To achieve this goal, I propose to set up a directory called "legacyclasses" where we can put classes represent old format such as legacytestingoutcome.php, to enable database created by older versions of coderunners to be able to be read.

Another example is the question type fields in pre-coderunner 2.4, which you have stripped after coderunner 3.0.  At the moment, sysadmins will need to set up a separate VM with coderunner pre 3.0 to read in the course and re-export to a new format course.  Again, the class that allows reading in the old question type need to be reinstated, and go to the "legacyclasses" directory.

**Comment by trampgeek** [comment]
Sorry, Kai-Cheung, but as I said in a separate email to you, I'm not sympathetic to this proposal. Your University was one of the very early adopters of CodeRunner (for which I'm grateful) but you picked it up during the early development stages. I've made several significant changes since then, though I've always tried to ensure that people could continue to import questions from previous versions of the code for at least a couple of years.

CodeRunner was made compliant with Moodle coding standards around December 2016 and was accepted into the official plug-in repository in February 2017. With the number of institutions using CodeRunner now rising rapidly I certainly accept that I have a responsibility to maintain backward compatibility. However, your concerns all relate to much earlier versions of the code, written prior to January 2015. Even there, if I understand correctly, you have a viable way of copying questions across from your earlier servers to the latest version via an intermediate version of CodeRunner. Your only real problem is that you can't inspect the actual student submissions and their grading results from your pre-2015 CodeRunner version. 

For maintainability I like to keep my code as clean possible. I don't wish to muddy it by including testing classes relating to a much earlier version of CodeRunner, particular when those classes do not conform to Moodle coding standards.

I suspect you're the only institution wishing to keep copies of all student CodeRunner submissions that were made to those much earlier versions of CodeRunner. That's not something we've wanted to do even here at Canterbury. However, if there are other users with similar problems reading this posting, please correct my wrong assumption, and I'll give some thought to the best way to import the old-format test results into the latest version of the code.

Richard
