### ISSUE TITLE
Hard-wired English language strings 

### ISSUE THREAD

**Issue by germanvaleroelizondo** [trampgeek/moodle-qtype_coderunner#54]
Hi,
After translating in AMOS most of the English language strings for this plugin, I found that the user sees some untranslated English language strings in the 'Question type details' section, that belong to the text that describe the builtin PROTOTYPES.

You can easily check this using the mexican Spanish language pack.

For example, in coderunner\db\builtin_PROTOTYPES.xml
 Line 795:       <text>A generic Python3 question. For each test case, the

If it is not terribly complicated, I think this plugin would be even better if these hard-wired English language strings could be made into string variables, so that they would be available in AMOS for translation into other languages different from English. Most of the strings from this plugin have already been translated into German, Romanian and Mexican Spanish :) 

Thanks in advance for your help.

**Comment by trampgeek** [comment]
Hi Germán

Firstly, many thanks for translating most of the English language strings - that's a great service to the Spanish-speaking community.

You raise a good point regarding the strings in the question prototypes. However, I'm not sure at this stage how to deal with the problem. The question prototypes are essentially outside the plugin - they're just like normal questions, except they have a checkbox to say they can be used as prototypes for other questions. The "Question details" panel is obtained just by displaying the text of the question - it's a convention that you should provide helpful documentation as question text within question prototypes.

As a stopgap measure for your own institution, you could just login as an administrator and translate the text in each of the prototype questions, using the usual question authoring interface. However, that's clearly not a good solution longer term. Since I describe the prototype questions as being "built-in", there should be a way to have the question text subject to the AMOS process.

I'll have to think about this. It certainly won't be trivial to fix, so please don't expect a solution until the end of the year at the earliest. But I'll leave the issue open in the meantime.

Thanks again for raising it.

Regards

Richard

**Comment by trampgeek** [comment]
On reflection it mightn't be too hard at all. I could construct a language string from the question type, such as _questiontype_c_program_ and look for that in the language strings. If found, display that. If not, render the question text. I'll look into it when I next have some development time. We've just started a new term today, so not for a few weeks.

**Comment by germanvaleroelizondo** [comment]
Thanks a lot. 
I will be looking forward to your next plugin version.

**Comment by trampgeek** [comment]
The latest version of the plugin has language strings for all the built-in question types. So I'm closing this issue. Thanks for raising it.

**Comment by germanvaleroelizondo** [comment]
I just saw the new strings in AMOS. I will start the es_mx translations.
Thanks a lot.
