### ISSUE TITLE
This plugin does not implement the Moodle privacy API

### ISSUE THREAD

**Issue by germanvaleroelizondo** [trampgeek/moodle-qtype_coderunner#57]
This plugin does not implement the Moodle privacy API. If this plugin stores any personal data it will not be able to be exported or deleted through Moodle's privacy system.

It would be nice if you can fix this.

Thanks in advance.

**Comment by trampgeek** [comment]
I'm not familiar with the privacy API, but I'd have thought that since CodeRunner is just a question type, storing its data in the usual question type DB tables, any privacy issues were handled by the standard Moodle question super-type(s). The extra DB tables that CodeRunner uses do not contain any personal data - simply settings for the question. The jobe server, used to run student submissions is stateless, so it also does not store personal data.
I am perhaps missing the point - would you be able to clarify what you think CodeRunner is not doing that it should be doing, please?
Richard

**Comment by germanvaleroelizondo** [comment]
I am sorry I did not explain myself clearly :(

Your plugin just needs to tell Moodle that it does not store any personal data (the way Moodle 3.5 expects your plugin to be coded).

Please look at the image for the (nice example) RegExp question type example at https://docs.moodle.org/35/en/admin/tool/dataprivacy/pluginregistry.

Please look at what this plugin programmer did at https://github.com/ndunand/moodle-qtype_regexp/commit/6d7d9b05c198811cb80a9efd048a7faff6ba77f4

**Comment by trampgeek** [comment]
Hi German

Sorry about the delay - had to put this on hold for a bit due to other work pressure. But I've done it now and it will go out in the next push, hopefully within a couple of weeks.

Thanks for alerting me to the need.

Richard
