### ISSUE TITLE
Coderunner Exception after installation

### ISSUE THREAD

**Issue by Feizi-AT** [trampgeek/moodle-qtype_coderunner#80]
I just installed coderunner on a fresh installed moodle server and get the following Exceptions. 
Exception - Class 'qtype_coderunner\constants' not found and  Exception - Class 'qtype_coderunner_sandbox' not found. What can i do to resolve this?

**Comment by trampgeek** [comment]
Can you please let me know:

1. What version of Moodle you're running?
2. How you installed CodeRunner (i.e., did you clone it from github or install the version from the Moodle plugin repository)?
3. What you did to trigger that particular error?  (I would like a repeatable sequence of steps, please)

If you are able to get a complete exception traceback, that would be helpful too.

**Comment by Feizi-AT** [comment]
1. I am running 3.3 on centos 7
2. I downloaded the zip files from git
3. when I added the plugins and moodle asked to upgrade it's database (it did that successfully) the Exception - Class 'qtype_coderunner_sandbox' not found error happend and the other one comes up when i try to add a question using coderunner

**Comment by trampgeek** [comment]
The current version of CodeRunner requires Moodle 3.4 or later. However, 
that doesn't explain those particular errors, which look like to be from 
a faulty install process. The class loader should automatically find 
those files so either they're missing or they (or the path to them) 
isn't readable by the web server.

If this is a test server generated for the purpose of testing 
CodeRunner, I'd suggest you discard the current server, start over and 
install CodeRunner from the Moodle Plugins Repository 
<https://moodle.org/plugins/pluginversions.php?plugin=qtype_coderunner>, 
choosing the most recent version compatible with Moodle 3.3.

Otherwise, you'll first need to find what is broken with the current 
install and when that's fixed you'll need to deal with the 
incompatibilities between the current version and Moodle 3.3

If you wish to debug the current state of affairs, ... firstly, in 
<moodlehome>/question/type/coderunner, can you check that there's a 
directory 'classes' that's readable by Apache2? If so, let's see a 
listing of that directory.

**Comment by Feizi-AT** [comment]
So i tried to install the plugin via the Moodle website and it just worked. Thank you for your help and fast response and have a nice day!

**Comment by trampgeek** [comment]
Good to hear. Enjoy!
