### ISSUE TITLE
Make time limit a float instead of an int?

### ISSUE THREAD

**Issue by fstonedahl** [trampgeek/moodle-qtype_coderunner#84]
Any reason that the "TimeLimit (secs)" setting (under Advanced Customization) couldn't be a floating point number (e.g. 0.5 seconds), instead of being restricted to an integer (as it currently is)?

**Comment by trampgeek** [comment]
CodeRunner passes the time limit to Jobe. This uses it for setting the Linux resource limits, specifically RLIMIT_CPU. This is defined to be the "limit, in seconds, on the amount of CPU time that the process can consume", and it has to be an integer. 

Somewhat confusingly, the runguard sandbox which Jobe uses internally takes floating point values for timeouts, but internally it adds 1 and truncates to an integer. So actually the minimum timeout is currently 2 secs! It is possible to use cgroups instead of ulimits for finer-grained resource control but installation of jobe would then become more complex. I'm not keen to head down that path until I have a compelling reason. Do you actually need fractions of a second timeouts?

For now, anyway, I'm afraid you'll have to live with integer timeouts.

**Comment by fstonedahl** [comment]
No, I don't need it.  I'm just trying to write some questions involving algorithms/data structures, where I want the students to come up with a O(N) or O(N log N) solution, instead of O(N^2).  I can use a large test case with the 1 sec (I guess actually 2 sec!) limit to do this, but I figured that was a bit wasteful on the server load, and if I could set the limit to 0.1 seconds instead, that would accomplish the same goal.

But no, it's not important -- I was just guessing it would be an easy change, but I can see I was wrong.

I also presume that I could write a custom Python template using subprocesses could be used as a work-around (without changing CodeRunner at all), but again, I don't think it's worth the trouble.

(I was mildly tempted to try to write a custom grading template that assigned points based on how fast the student's submission ran, but given all the vagaries of getting accurate timing data, it seemed like this might not be consistent/fair enough for the students.)
