### ISSUE TITLE
CodeRunner makes inappropriate use of global $USER

### ISSUE THREAD

**Issue by timhunt** [trampgeek/moodle-qtype_coderunner#86]
In start_attempt, CodeRunner intends to store the user id of the user who's quiz attempt this is in a variable _STUDENT.

And, it assumes that global $USER will be set to the user who is attempting the quiz. This is not a safe assumption, and we just hit it in a plugin we were making: (https://github.com/moodleou/moodle-quiz_answersheets. Specifically see the hack we had to add in https://github.com/moodleou/moodle-quiz_answersheets/blob/master/classes/external.php.)

I don't really have a suggestion for how this feature can be made to work properly. I know this was something that was asked for, but the Moodle question system intentionally does not link question_attempt or question_usage to a userid, because when I was implemening the question system, I was aware of feature requests like group quiz attempts (https://tracker.moodle.org/browse/MDL-48699). The only reliable link from a question_attempt in a quiz, to userid is via question_attempt -> question_usage -> quiz_attempt, and of course that is quiz-specific, so also something you should refer to in a question type. And anyway, that would change if group quiz attempts were implemented.

**Comment by trampgeek** [comment]
Many thanks for identifying the problem Tim.

Firstly a couple of questions:

1. When validating a question that an author is editing which has attachment files, I need to get files from the user draft area. I do this by first getting the context as context_user::instance($USER->id). Am I right in thinking that that use at least is safe?

1. Another use is in _save_question_options_, where I assume that $USER->id exists if this is a real call to the method, rather than a spurious call during unit testing. Is that assumption safe?

Assuming those two are OK, where I think I have a problem is with all the uses of $USER that are related to the Twig STUDENT variable. That variable is used by various question authors for customising questions to a particular student or to set a random-number seed so that all questions in a particular student's quiz can be locked into the same question scenario.

Studying the code I see a regression that I introduced a couple of months ago when I refactored for the latest version of Twig. [I assume you're testing with the latest version?] My intention is (or was) to lock the STUDENT variable to a particular question attempt in _qtype\_coderunner\_question::start_attempt()_ and recover that locked-in value in the _apply\_attempt\_state(). I should have used that recovered value throughout the rest of the code in question.php and twig.php but when I refactored I forgot the reason for doing things that way and used the global $USER variable again. My bad.

Assuming I fix that regression and go back to establishing the current user in _start\_attempt()_, is it safe to get the userid from the _question\_attempt\_step parameter to _start\_attempt_, and use that to read the user info from the database? I appreciate that the user will be the teacher when previewing. All I require is that a plausible user variable gets locked in throughout the duration of the question attempt and when a teacher is reviewing the student's code. 

There is another flaky use of $USER for my new programming contest question type, but this is an unsupported and undocumented feature so I'm not worrying about that for now.

**Comment by timhunt** [comment]
You first couple of questions are about when a teacher edits a question. No problem using $USER there.

I am looking at a version of CodeRunner that sets STUDENT in start_attempt, and I am saying that is not safe.

If what you are trying to do is sychronise a random seed between questions, the way we have done that in other question types (e.g. STACK, Variable numeric *) is to have a field 'variantsselectionseed' on the question form (https://github.com/maths/moodle-qtype_stack/blob/master/edit_stack_form.php#L217) and then in the question class, implement the get_variants_selection_seed and get_num_variants methods (https://github.com/maths/moodle-qtype_stack/blob/master/question.php#L848). (1 million variants seems to be the conventional number of variants to declare if you don't have a small finite number.)

Then, the integer $variant passed to start_attempt will be a 'random' number between 1 and get_num_variants inclusive. But, if two questions in the same quiz attempt return the same get_variants_selection_seed, then they will get the same 'random' variant.

This is better than using $USER->id, because as well as having all questions in the quiz use the same seed, it also lets you do things like having questions 1-5 use one seed, but then independently questions 6-10 use a different seed. However, it does require the teacher to set it up. It also allows students to get different random variants if they make a second attempt at the same quiz, which is probably makes the quiz more effecive practice for students, if that is what the quiz is for.

However, swtiching from the current scheme to the Moodle approve one is going to be a pain. A cheat to maitain backwards compatbility would be to set STUDENT = 'student' . $variant; for newly created attemtps, but to mark the STUDENT template variable as deprecated.)

But what I would actually recomment is to create a new template variable called 'VARIANT' or some such, which passes the actual Moodle variant number to the template. It might also be worth adding an extra setting to the question form 'Number of variants' (default 1) so that for questions with a small number of variants, they can get passed in the exact variant number. The reason you would want to do that is that the Quiz statistics report knows about variants. So, if your question has, say, 3 variants, the quiz statistics will break down the data like average score by variant, and you can see immiately if students are finding one particuarl varian much easier or harder than the rest. (With a million variants, this break-down is unhelpful, but you can ignore it.)

Sorry it did not arise that I could explain all this to you when it would have been timely.

question_attempt_step->userid is meant to be the user who performed that specific action to the question. So in the case where a student is attempt a quiz themselves, that will mostly be the student's user id, but then if a teach manually grades the question after it is submitted, then the step that records that action will have the teacher's user id. I would not recommend relying on that here.

**Comment by trampgeek** [comment]
Many thanks for the thorough explanation, Tim. It does look like I should implement the standard _variant_ system for compatibility with the other question types and also to provide a more obvious path for newcomers.

However, I would also like to maintain some sort of STUDENT variable if at all possible, partly so as not to break existing questions but also because it has other use cases. For example, one of our lecturers gets students to write code that outputs their own name (taken from the STUDENT variable). As a cunning extra he embeds that name in a "Written by ..." docstring preloaded into the answerbox. It's amazing how many students copy their friend's answer, change it to print their own name, but forget to update the docstring!

In your last paragraph you say that  question\_attempt_step->userid is unsafe because of (say) manual marking. But CodeRunner doesn't support manual marking, only post-submission manual grade changing, and of course question review. If I lock in the STUDENT variable (from question\_attempt_step->userid rather than $USER) in start\_attempt(), and pick up that value again in apply\_attempt\_state(), I still don't see a scenario that breaks. Certainly this approach (but using $USER) has worked fine for years - when teachers review student submissions they always see the same STUDENT variable as the student got. So can you clarify the fail case here for me, please?

**Comment by timhunt** [comment]
question_attempt_step->userid is definitely the least bad option.

The manual grading example was not meant to be an example of something that would break coderunner, but the example that justifies the existence of $step->userid exists.

Currently question_attempt_step->userid would not work in the case of our quiz_answersheets plugin (linked above) but thinking about this on my cycle ride home, I decided it was reasonable to log https://tracker.moodle.org/browse/MDL-67155 and submit a fix (which is pretty simple).

**Comment by trampgeek** [comment]
Great service, many thanks Tim. I've implemented the change and pushed it to github in the development branch, and installed it on our production server. Unless anything weird happens in the next few days I'll merge back into master, push to github and add to the Moodle repository.
